version: '3.8'

services:
  web:
    image: php:8.2-apache
    container_name: aerohuila_app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    # Habilitamos extensiones necesarias para MySQL y subida de archivos
    command: >
      bash -c "docker-php-ext-install mysqli pdo pdo_mysql && apache2-foreground"
    platform: linux/arm64/v8  # Optimizado para tu chip M4

  db:
    image: mysql:8.0
    container_name: aerohuila_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aerohuila_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    platform: linux/x86_64 # Usamos emulaci√≥n x86 para compatibilidad de MySQL 8 estable

volumes:
  db_data: